---@module 'luassert'

local util = require('tests.util')

describe('inline code', function()
    it('space', function()
        util.setup.text({ '` code `' })
        local marks = util.marks()
        marks:add({ 0, 0 }, { 0, 8 }, util.highlight('code'))
        marks:add({ 0, 0 }, { 1, 2 }, util.conceal())
        marks:add({ 0, 0 }, { 6, 7 }, util.conceal())
        util.assert_view(marks, { 'code' })
    end)

    it('space nested', function()
        util.setup.text({ '`` `code` ``' })
        local marks = util.marks()
        marks:add({ 0, 0 }, { 0, 12 }, util.highlight('code'))
        marks:add({ 0, 0 }, { 2, 3 }, util.conceal())
        marks:add({ 0, 0 }, { 9, 10 }, util.conceal())
        util.assert_view(marks, { '`code`' })
    end)

    it('space left only', function()
        util.setup.text({ '` code`' })
        local marks = util.marks()
        marks:add({ 0, 0 }, { 0, 7 }, util.highlight('code'))
        util.assert_view(marks, { ' code' })
    end)

    it('space right only', function()
        util.setup.text({ '`code `' })
        local marks = util.marks()
        marks:add({ 0, 0 }, { 0, 7 }, util.highlight('code'))
        util.assert_view(marks, { 'code' })
    end)

    it('space no body', function()
        util.setup.text({ '`  `' })
        local marks = util.marks()
        marks:add({ 0, 0 }, { 0, 4 }, util.highlight('code'))
        util.assert_view(marks, { '' })
    end)
end)
