name: Bug Report
description: File a bug / issue
title: "bug: "
labels: [bug]
body:
  - type: input
    attributes:
      label: Neovim version (nvim -v)
      placeholder: 0.10.0
    validations:
      required: true
  - type: input
    attributes:
      label: Neovim distribution
      placeholder: N/A, LazyVim, NvChad
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system
      placeholder: MacOS
    validations:
      required: true
  - type: input
    attributes:
      label: Terminal emulator / GUI
      placeholder: WezTerm
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A description of what the bug is. Please provide markdown as text in addition to screenshots & include any related errors you see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Healthcheck output
      description: Output of :checkhealth render-markdown
      render: text
    validations:
      required: true
  - type: textarea
    attributes:
      label: Plugin configuration
      description: Your configuration for this plugin (:RenderMarkdown config).
      render: lua
    validations:
      required: true
  - type: textarea
    attributes:
      label: Plugin error log
      description: Error log (:RenderMarkdown log) if empty put N/A.
      render: text
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Confirmations
      options:
      - label: I have updated this plugin to the latest version using my plugin manager
        required: true
      - label: I have provided the text contained in all screenshots as raw text in this issue. This means if there is a screenshot below it is the copy pasted contents of the file in the screenshot. I understand that my issue will be closed if I have not.
        required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Any additional information you would like to provide.
    validations:
      required: false
